# Configuration flags and values for app features

#Specifies the version of the app
include Makefile.version

# Enable debug output in speculos and other development features
APP_TESTING ?= 0

PRODUCTION_BUILD ?= 0
